CREATE DATABASE IF NOT EXISTS app;
CREATE DATABASE IF NOT EXISTS dev_app;
CREATE DATABASE IF NOT EXISTS performance_test;
GRANT ALL PRIVILEGES ON app.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON dev_app.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON performance_test.* TO 'user'@'%';

FLUSH PRIVILEGES;